[profile.default]
  src = "contracts"
  out = "out"
  solc_version = "0.8.19"
  via-ir = true

[fmt]
  line_length = 119
  tab_width = 4
  wrap_comments = false

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
