[profile.default]
src = 'contracts'
out = 'out'
solc_version = "0.8.19"
via-ir = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
