[profile.default]
  src = "contracts"
  out = "out"
  solc_version = "0.8.19"
  via-ir = true

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 119
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  goerli = "${GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
